### ISSUE TITLE
Apple M1 issue: runtime: failed to create new OS thread (have 2 already; errno=22)

### ISSUE THREAD

**Issue by 21jake** [wodby/postgres#1]
I couldn't run wodby/postgres image on my M1 Macbook (MacOs Big Sur, 11.3.1).
My Docker version is 3.3.3 ([Docker Desktop for Apple silicon)](https://docs.docker.com/docker-for-mac/apple-silicon/)
The container won't start and emits these errors

`ovhome_postgresql | runtime: failed to create new OS thread (have 2 already; errno=22)`
`vovhome_postgresql | fatal error: newosproc`
`vovhome_postgresql |`
`vovhome_postgresql | runtime stack:`
`vovhome_postgresql | runtime.throw(0x6249a0, 0x9)`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530 +0x90`
`vovhome_postgresql | runtime.newosproc(0xc820024000, 0xc820033fc0)`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/os1_linux.go:149 +0x18c`
`vovhome_postgresql | runtime.newm(0x676240, 0x0)`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1513 +0x135`
`vovhome_postgresql | runtime.main.func1()`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:125 +0x2c`
`vovhome_postgresql | runtime.systemstack(0x732c00)`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:291 +0x79`
`vovhome_postgresql | runtime.mstart()`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1048`
`vovhome_postgresql |`
`vovhome_postgresql | goroutine 1 [running]:`
`vovhome_postgresql | runtime.systemstack_switch()`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:245 fp=0xc82001e770 sp=0xc82001e768`
`vovhome_postgresql | runtime.main()`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:126 +0x62 fp=0xc82001e7c0 sp=0xc82001e770`
`vovhome_postgresql | runtime.goexit()`
`vovhome_postgresql | /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001e7c8 sp=0xc82001e7c0`
`vovhome_postgresql exited with code 2`

**Comment by csandanov** [comment]
Looks like you're using an outdated image, what's your image tag?

**Comment by 21jake** [comment]
my `$POSTGRES_TAG` is `11-1.5.0`

Edit: Okay so I switch the image tag to `13-1.21.5` and it works. Thank you for the suggestion!

**Comment by daemon1981** [comment]
I've got the same issue with an older version 9.5.5. With the alpine version "9.5.5-alpine" it is working
